services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: SIBUR_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/sibur111/backend:main
    build: .
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/SIBUR_DB
      DB_HOST: db
    ports:
      - '8000:8000'

volumes:
  postgres-data: