"""Fix2 chemical tables

Revision ID: 061df323133f
Revises: 27a70aba6695
Create Date: 2025-07-08 10:50:22.419111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061df323133f'
down_revision: Union[str, Sequence[str], None] = '27a70aba6695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicalobjects', sa.Column('source_check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemicalobjects', 'source_check')
    # ### end Alembic commands ###
