"""Add PercentChemicalElements table

Revision ID: 0f7c3c55e6ea
Revises: 9f118041c5ab
Create Date: 2025-07-09 01:41:59.516696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7c3c55e6ea'
down_revision: Union[str, Sequence[str], None] = '9f118041c5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percentchemicalelements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('main_percent', sa.Float(), nullable=False),
    sa.Column('Fe_percent', sa.Float(), nullable=False),
    sa.Column('Si_percent', sa.Float(), nullable=False),
    sa.Column('K_percent', sa.Float(), nullable=False),
    sa.Column('Ca_percent', sa.Float(), nullable=False),
    sa.Column('Mg_percent', sa.Float(), nullable=False),
    sa.Column('Na_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['chemicalobjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chemicalobjects', 'molar_mass',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicalobjects', 'molar_mass',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('percentchemicalelements')
    # ### end Alembic commands ###
