"""Initial chemical tables

Revision ID: 20ad59d7e7c7
Revises: 2249226fc9c6
Create Date: 2025-07-04 18:40:30.428369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ad59d7e7c7'
down_revision: Union[str, Sequence[str], None] = '2249226fc9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemicalobjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chemical_formula', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemicaloperations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('additional_conditions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['chemicalobjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemicaloperations')
    op.drop_table('chemicalobjects')
    # ### end Alembic commands ###
