"""Fix1 chemical tables

Revision ID: 27a70aba6695
Revises: 20ad59d7e7c7
Create Date: 2025-07-05 20:48:47.690510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a70aba6695'
down_revision: Union[str, Sequence[str], None] = '20ad59d7e7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicaloperations', 'additional_conditions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicaloperations', 'additional_conditions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
