"""Fix chemical objects source_check

Revision ID: 6654a4d3d9cd
Revises: c982b338c99d
Create Date: 2025-07-20 12:27:01.812242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6654a4d3d9cd'
down_revision: Union[str, Sequence[str], None] = 'c982b338c99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicalobjects', 'source_check',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicalobjects', 'source_check',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
