"""Fix4 Chemical Tables

Revision ID: 785b67ff517f
Revises: 83c97530b837
Create Date: 2025-07-10 11:54:36.822378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785b67ff517f'
down_revision: Union[str, Sequence[str], None] = '83c97530b837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chemicaloperations_target_id_fkey'), 'chemicaloperations', type_='foreignkey')
    op.create_foreign_key(None, 'chemicaloperations', 'chemicalobjects', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('percentchemicalelements_type_id_fkey'), 'percentchemicalelements', type_='foreignkey')
    op.create_foreign_key(None, 'percentchemicalelements', 'chemicalobjects', ['type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'percentchemicalelements', type_='foreignkey')
    op.create_foreign_key(op.f('percentchemicalelements_type_id_fkey'), 'percentchemicalelements', 'chemicalobjects', ['type_id'], ['id'])
    op.drop_constraint(None, 'chemicaloperations', type_='foreignkey')
    op.create_foreign_key(op.f('chemicaloperations_target_id_fkey'), 'chemicaloperations', 'chemicalobjects', ['target_id'], ['id'])
    # ### end Alembic commands ###
