"""Fix3 chemical tables

Revision ID: 9f118041c5ab
Revises: 061df323133f
Create Date: 2025-07-09 01:04:03.830271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f118041c5ab'
down_revision: Union[str, Sequence[str], None] = '061df323133f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicalobjects', sa.Column('molar_mass', sa.Integer(), nullable=True))
    op.alter_column('chemicalobjects', 'source_check',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemicalobjects', 'source_check',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('chemicalobjects', 'molar_mass')
    # ### end Alembic commands ###
