"""Update user table

Revision ID: e9710002e27b
Revises: 5a349e606f7f
Create Date: 2025-07-03 11:51:44.925320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9710002e27b'
down_revision: Union[str, Sequence[str], None] = '5a349e606f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('user_data', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'user_data')
    # ### end Alembic commands ###
